In [37]:
import torch
import numpy as np

자동 미분

In [38]:
x = torch.ones(2, 2, requires_grad=True)

print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [39]:
z = 3*(x+2)**2

print(z)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)


In [40]:
# x.backward() == x.backward(torch.tensor(1))
z.backward(torch.tensor([[1, 1], [1, 0.1]]))

print(x.grad)

tensor([[18.0000, 18.0000],
        [18.0000,  1.8000]])


In [41]:
print(x.norm())

tensor(2., grad_fn=<NormBackward0>)


In [42]:
with torch.no_grad():
    # don't track
    y1 = x+3
y2 = x**2

In [43]:
print(y1.requires_grad)
print(y2.requires_grad)

False
True


In [47]:
x1 = x.detach()

print(x1.requires_grad)
print(x1.eq(x))

False
tensor([[True, True],
        [True, True]])
