In [92]:
import torch
import numpy as np

In [93]:
x = torch.empty(5, 3) # not initialized
# raw memory value

# torch.{fill type}
# empty, ones, zeros, full, rand, randint, randn
print(x)

tensor([[1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39],
        [9.6429e-39, 1.0653e-38, 1.0469e-38]])


In [94]:
y = torch.ones_like(x, dtype=torch.long)
# torch.{fill type}_like
# follow dtype, size, device, etc
print(y)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [95]:
a = y.new_full((3, 4), 3)
# x.new_{fill type}
# follow dtype, device, etc
print(a)

tensor([[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]])


In [96]:
print(x.size(), y.size(), a.size())

torch.Size([5, 3]) torch.Size([5, 3]) torch.Size([3, 4])


In [97]:
b = torch.ones_like(a)
print(a+b)
print(torch.add(a, b))
print(b.add(a))

c = torch.empty_like(a)
torch.add(a, b, out=c)
print(c)
# don't change a, b

print(a, b, sep="\n")

tensor([[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]])
tensor([[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]])
tensor([[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]])
tensor([[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]])
tensor([[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]])
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])


In [98]:
# x.{operation}_ : in-place method
b1 = torch.ones_like(b)
b1.add_(a)
#change b1

print(a, b1, sep="\n")

tensor([[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]])
tensor([[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]])


In [99]:
print(b1[2,3])

print(b1[2,3].item())

tensor(4)
4


In [100]:
b2 = b1.view(2, 3, -1)
print(b2)

tensor([[[4, 4],
         [4, 4],
         [4, 4]],

        [[4, 4],
         [4, 4],
         [4, 4]]])


In [101]:
b3 = b1.numpy()
print(b3)

b1.add_(a)

print(b1, b3, sep="\n")

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]
tensor([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]])
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
