In [1]:
import torch

* `torch.add(tensor, other, out, ...)`
* tensor와 other을 add 연산함
* 기본적인 연산의 경우에는 +, -등의 연산자를 사용한 연산 가능
* `{tensor}.add(other, ...)` 의 형식으로도 쓸 수 있음
* `{tensor}.add_(other, ...)` 처럼 함수 뒤에 _를 붙이면 tensor의 값을 변화시킴(+=)
* out 파라미터를 이용해 결과값을 지정한 변수에 저장할 수 있음
* out 파라미터는 `torch.add()` 형태의 함수에서만 사용 가능

In [13]:
a = torch.rand(2, 3)
b = torch.ones_like(a)
c = torch.empty_like(a)

print(a, "\n")

# don't change a, b
print(a+b)
print(torch.add(a, b, out=c))
print(c)
print(a.add(b))
print(a, "\n")

# change a
print(a.add_(b))
print(a)

tensor([[0.3799, 0.7715, 0.0474],
        [0.8615, 0.9405, 0.8682]]) 

tensor([[1.3799, 1.7715, 1.0474],
        [1.8615, 1.9405, 1.8682]])
tensor([[1.3799, 1.7715, 1.0474],
        [1.8615, 1.9405, 1.8682]])
tensor([[1.3799, 1.7715, 1.0474],
        [1.8615, 1.9405, 1.8682]])
tensor([[1.3799, 1.7715, 1.0474],
        [1.8615, 1.9405, 1.8682]])
tensor([[0.3799, 0.7715, 0.0474],
        [0.8615, 0.9405, 0.8682]]) 

tensor([[1.3799, 1.7715, 1.0474],
        [1.8615, 1.9405, 1.8682]])
tensor([[1.3799, 1.7715, 1.0474],
        [1.8615, 1.9405, 1.8682]])


* `torch.clamp(tensor, min=-inf, max=inf, ...)`
    * min 이하의 값은 min으로, max 이상의 값은 max로 바꿈
    * ex) relu 함수를 구현하는데 사용

In [4]:
x = torch.rand(2, 3)*2-1

print(x)
print(x.clamp(min=0.3, max=0.6))
print(x.clamp(min=0)) # relu function

tensor([[ 0.6781,  0.5581,  0.8438],
        [ 0.6572,  0.9216, -0.6582]])
tensor([[0.6781, 0.5581, 0.8438],
        [0.6572, 0.9216, 0.0000]])
tensor([[0.6000, 0.5581, 0.6000],
        [0.6000, 0.6000, 0.3000]])


* `torch.mm(tensor, other, ...)`
    * 